# Generated by Django 6.0.3 on 2026-06-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trendkart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
        ),
    ]
