# Generated by Django 6.0.3 on 2026-07-05 06:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trendkart', '0008_contact_mobile_product_sku_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=50, null=True),
        ),
    ]
