# Generated by Django 6.0.3 on 2026-07-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trendkart', '0010_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=30),
        ),
    ]
